### PR TITLE
fix: render decimal point properly

### PR DESCRIPTION
**Pull request by pjc0247**
render the decimal point as '.' instead of '0'.

### CODE REVIEW

**Review by heyman333 — APPROVED** [review]
Thanks for the simple solution :D

**Comment by heyman333** [comment]
This closes #9

**Comment by heyman333** [comment]
```js
import React from "react";
import AnimatedNumbers from "./module";
import "./App.css";

function App() {
  const [num, setNum] = React.useState(1.4);
  return (
    <div className="container">
      <AnimatedNumbers
        includeComma
        animateToNumber={num}
        fontStyle={{ fontSize: 32 }}
        // configs={[
        //   { mass: 1, tension: 220, friction: 100 },
        //   { mass: 1, tension: 180, friction: 130 },
        //   { mass: 1, tension: 280, friction: 90 },
        //   { mass: 1, tension: 180, friction: 135 },
        //   { mass: 1, tension: 260, friction: 100 },
        //   { mass: 1, tension: 210, friction: 180 },
        // ]}
        configs={(number, index) => {
          return { mass: 1, tension: 230 * (index + 1), friction: 140 };
        }}
      ></AnimatedNumbers>
      <div>
        <button onClick={() => setNum((state) => state + 1.39)}>+</button>
        <button onClick={() => setNum((state) => state - 1)}>-</button>
      </div>
    </div>
  );
}

export default App;
```
we have this problem when testing
If you're interested, I hope you can contribute more!



https://user-images.githubusercontent.com/22214150/145700752-ca4fae6e-4b96-4757-8156-de2bdb8b75ca.mov

**Comment by pjc0247** [comment]
@heyman333 sure, i'll take a look and create an another PR soon.

**Comment by pjc0247** [comment]
It wasnt a bug related this PR.

Please add `<span>{num}</span>` to debug the value. (which will display `5.569999999999999`).

**Comment by pjc0247** [comment]
I also submitted a new PR since i've deleted the original branch. (the files in this PR can't be modified anymore)

**Pull request closed without merging**
